### PR TITLE
added pull request template file

### PR DESCRIPTION
**Pull request by treilly94**
# Context
Added this pull request template #18 

# How to review
Look at the template and see if you like it
# Checklist
- [ ] Code has been tested
- [ ] Bug/Feature is tested/reviewed against acceptance criteria
- [ ] Bug/Feature passes all tests and passes ci/cd analysis tools
- [ ] Code is review ready
- [ ] Bug/Feature is documented (Handover/Knowledge share included)

### CODE REVIEW

**Comment by emilioward** [comment]
I like the checklist. I would have headers that say:

### What is the context of this PR?
Describe what you have changed and why, link to other PRs or Issues as appropriate.

### How to review 
Describe the steps required to test the changes (include screenshots if appropriate).

So that its clear for other developers what changes you've made and make it easier for us to test your PR's

**Comment by treilly94** [comment]
Something a bit more like this?

**Comment by emilioward** [comment]
Quick question. How many approval are we looking to have before merging going forward?

**Comment by srussell91** [comment]
3 maybe? 2 + 1 if there's a disagreement, or just 2 normally and 3 if there's a disagreement?

**Comment by dcdarrell9** [comment]
I'm happy with 1 on minor changes and 2 on anything else, ideally we can resolve any conflicts, but it's all about using some common sense. You don't need 2/3 approvals for comment fixes but you would if you changed the entire api structure etc

**Pull request merged**
