### PR TITLE
License

### PR DESCRIPTION
**Pull request by treilly94**
#11 

Added a licence and documentation around the decision.

### CODE REVIEW

**Comment by treilly94** [comment]
This should probably be merged after #16 has been merged and this branch has been brought upto date with master because I stupidly included the changes from that branch.

**Comment by dcdarrell9** [comment]
I'm good with this Licence/License, what happens if we decide that we want to go closed instead of open source?

**Comment by treilly94** [comment]
Not sure. 
Apparently the developers technically cant violate the agreement its just a shitty thing to do
https://www.gnu.org/licenses/gpl-faq.html#DeveloperViolate

**Comment by treilly94** [comment]
Could always go MIT. Then if we wanted to make a closed source polished copy we could just fork it into a private repo and change the licence
https://choosealicense.com/licenses/mit/

**Comment by dcdarrell9** [comment]
@emilioward @KayleighB94 @srussell91 What's your opinion on a Licence? I'm thinking MIT as well now

**Comment by srussell91** [comment]
Only thing I'm not sure of is someone else being able to make a closed source version, but I suppose that's a catch for leaving the possibility of us releasing closed source versions.

**Comment by treilly94** [comment]
Changed it to MIT to allow people to make closed source versions.

**Comment by dcdarrell9** [comment]
@treilly94 Plus it's Licence for UK and License for US :upside_down_face:

**Pull request merged**
